### ISSUE TITLE
please support persion(farsi) language :: fa-IR

### ISSUE THREAD

**Issue by bugbounted2022** [RHVoice/RHVoice#591] opened 2022-07-02 14:14 UTC
Hi [RHVoice](https://github.com/RHVoice) ,
please support persion(farsi) language :: fa-IR
waiting for your commits :)
finest regards

**Comment by zstanecic** [comment] 2022-07-02 14:16
Hi,

As I know, the persian language is written with the Arabic alphabet, which needs a bit of neural network to distinguish words.

It is because when writing, we use only consonants, not wowels, am I right?

 

From: elmirarokni ***@***.***> 
Sent: Saturday, July 2, 2022 4:15 PM
To: RHVoice/RHVoice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RHVoice/RHVoice] please support persion(farsi) language :: fa-IR (Issue #591)

 

Hi RHVoice <https://github.com/RHVoice>  ,
please support persion(farsi) language :: fa-IR
waiting for your commits :)
finest regards

**Comment by elmirarokni** [comment] 2022-07-02 15:53
Hello again ,
yes exact but arabic not have 4 characters exist in persian , is گ چ پ ژ
& persian also  not have diacritic letters must use in arabic.

**Comment by zstanecic** [comment] 2022-07-29 12:39
btw, this is duplicate of 
#562 
So, it should be closed in favour of above.

**Comment by alex19EP** [comment] 2022-07-29 12:58
Duplicate of #562

**Closed by alex19EP** 2022-07-29 12:58 UTC
