### ISSUE TITLE
Support For The English RMS Voice

### ISSUE THREAD

**Issue by btman16** [RHVoice/RHVoice#482] opened 2022-02-22 08:18 UTC
Hello,

I'm using the RH Voice add-on with the NVDA screen reader and think this synthesizer definitely has a lot of potential.

It's very fast and responsive and it's nice to see that this is being actively worked on.

The English support offers the ability to use the Bdl voice which is very good. There is another voice which is part of that same set called RMS which is also another very good English voice and I was wondering if it's possible to add this into the available English voices for RH Voice by chance please?

I generally prefer this one because I feel it has slightly clearer pronunciations and so having this as another option would be a nice edition.

I want to thank everyone involved for their work on this synthesizer as it's continually improving.

Thank you very much for your time and I look forward to any input you may have concerning this.

Sincerely,

Brandon Tyson

**Comment by beqabeqa473** [comment] 2022-02-22 13:14
Hello.

I think we at RHVoice lab could try to train this voice, but the problem is that i wasn't able to find high quality dataset for that voice, only 16-khz

**Comment by btman16** [comment] 2022-02-22 14:05
Hello,

I think that it wouldn't sound bad if you were to try and train it
with the data even though it's only at 16 kHZ. The reason I think this
would be ok is that another synthesizer, MaryTTS, also uses this
voice, and at least when I hear that, it sounds like a very similar
synthesis method to what RH Voice is doing.

Thanks again for the quick response and I look forward to any input
you may have.

Sincerely,

Brandon Tyson

On 2/22/22, Beqa Gozalishvili ***@***.***> wrote:
> Hello.
>
> I think we at RHVoice lab could try to train this voice, but the problem is
> that i wasn't able to find high quality dataset for that voice, only 16-khz
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/482#issuecomment-1047784354
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
“Be what you are. This is the first step towards becoming better than you are.”
– J. C. Hare & A. W. Hare

**Comment by zstanecic** [comment] 2022-02-22 16:57
Hi Beqa,

Let me try to find it and train it.

At least, there should be 32 k original version.

**Comment by beqabeqa473** [comment] 2022-02-22 19:22
As i said, there is no other versions on festival website.

On 2/22/22, Zvonimir Stanečić ***@***.***> wrote:
> Hi Beqa,
>
> Let me try to find it and train it.
>
> At least, there should be 32 k original version.
>
>
>
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/RHVoice/RHVoice/issues/482#issuecomment-1048008900
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by zstanecic** [comment] 2022-02-22 19:50
One small hint:

During the training, you cannot apply world. During resynthesis, you will get only distorted buzzing.

Only old vocoder works there.

**Comment by datajake1999** [comment] 2022-02-24 17:27
Isn't the training data for some of the other voices such as BDL 16 K?

**Comment by zstanecic** [comment] 2022-03-20 14:02
Yes, bdl was trained using 16 K. I am preparing a fix for this issue. I am experimenting with some things.

**Comment by TheQuinbox** [comment] 2022-07-29 20:06
Any updates on this issue? I quite like this voice, and would love to see it in RHVoice

**Comment by zstanecic** [comment] 2022-08-08 08:51
Update of this issue:
due to lack of audio data, for 48 k training with new methods and approaches, please close this issue.
According to my training, 16 k is worse, compared to new voices we recently train.

**Comment by TheQuinbox** [comment] 2022-08-08 13:46
@zstanecic,
would it be lower quality than the Alan voice? If not, I see no reason to close it. I heard RMS in Festival, and it honestly sounded fine.

**Comment by zstanecic** [comment] 2022-08-08 14:34
RMS is the lower quality than Alan. It cannot be even compared.

**Comment by TheQuinbox** [comment] 2022-08-08 15:58
Hi @zstanecic,
I have attached an audio recording comparing the two voices. When hearing Alan, it definitely sounds downsampled, whereas RMS does not (it sounds similar to SLT and BDL) at least to my ear.

https://www.dropbox.com/s/vrfu8bt5xdyoi5w/RMSDemo2022-08-08_09-11-09.flac?dl=1

**Comment by king-dahmanus** [comment] 2022-08-09 13:24
@TheQuinbox those were the hts voices. This is slitely off topic but I need the latest festival addon for nvda 2021.3.5 and the way of using both clustergen and hts voices. Thanks
Also, rhvooice's version of alan has a lower quality than that of the one I've hird, or at least I think so

**Comment by zstanecic** [comment] 2022-08-22 15:41
This voice cannot be trained using pyworld. 
@alex19EP 
please close this issue as not planned.

**Closed** 2022-08-22 17:26 UTC
Labels: <Enhancement / Feature>, (P5 - Long-term), Help Wanted, Data: Voices
