### ISSUE TITLE
Strange pronunciation of multiple punctuation marks

### ISSUE THREAD

**Issue by SergTSA** [RHVoice/RHVoice#285] opened 2021-04-09 13:09 UTC
In Samsung TalkBack function multiple punctuation marks are pronounced like as "Символов Восклицательный знак три".

Android 11, Samsung Note 20 Ultra

alex19EP commented 1 hour ago
can you provide specific steps to repeat the error?

First you activate Talkback in Samsung Android11 by pressing Vol+ and Main. Then in browser open any text containing multiple punctuation marks with text - [for example](https://author.today/reader/113107/897645) 
you can see string 
`засранка, новую куртку!!!`
the last three explanation marks are read as 
`"Символов Восклицательный знак три`

**Comment by alex19EP** [comment] 2021-04-09 14:40
Duplicate of #284

**Closed by alex19EP** 2021-04-09 14:40 UTC

**Comment by alex19EP** [comment] 2021-04-09 14:42
let's not clutter the issue list.
