### ISSUE TITLE
Cannot build RHVoice in raspberry pi 4 Linux, SCons don't find Speech Dispatcher(Checking Speech Dispatcher version ... no)

### ISSUE THREAD

**Issue by Slva86** [RHVoice/RHVoice#276] opened 2021-03-22 17:14 UTC
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... yes
Checking for portaudio-2.0... yes
Checking Speech Dispatcher version ... no
('Configuring ', '/usr/src/RHVoice/src/core/config.h.in', 'into', '/usr/src/RHVoice/src/core/config.h', '...')
('Configuring ', '/usr/src/RHVoice/src/include/core/config.h.in', 'into', '/usr/src/RHVoice/src/include/core/config.h', '...')
IOError: [Errno 2] No such file or directory: '/usr/src/RHVoice/data/voices/victoria/voice.info':
  File "/usr/src/RHVoice/SConstruct", line 370:
    build_for_linux(base_env,vars)
  File "/usr/src/RHVoice/SConstruct", line 328:
    duplicate=0)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/usr/src/RHVoice/data/SConscript", line 42:
    props=RHVoiceInfoParser.parse(subdir.File(type+".info").abspath)
  File "/usr/src/RHVoice/site_scons/RHVoiceInfoParser.py", line 10:
    with io.open(path,"rt",encoding="utf-8") as f:

**Comment by alex19EP** [comment] 2021-03-22 18:57
you need to clone the repo with --recursive flag. or init and update submodules.

**Comment by alex19EP** [comment] 2021-03-22 19:00
Duplicate of #258

**Closed by alex19EP** 2021-03-22 19:00 UTC
